# name is required for byBuildNumber versioningScheme
# see https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml#package-versioning
name: $(Major).$(Minor).$(NumberOfBuilds)

variables:
  Major: '0'
  Minor: '1'
  MajorMinorVersion: ${{ format('{0}.{1}', variables['Major'], variables['Minor']) }}
  # NumberOfBuilds counter is automatically incremented by one in each pipeline execution
  # second parameter is a seed value, resets when referenced MajorMinorVersion is changed
  # see https://stackoverflow.com/a/56111209
  NumberOfBuilds: $[counter(variables['MajorMinorVersion'], 0)]

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: CI
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '*.sln'
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '*.sln'
      arguments: '--configuration Release --no-build --no-restore --collect:"XPlat Code Coverage" --settings:.runsettings'
  - task: PublishCodeCoverageResults@2
    inputs:
      summaryFileLocation: $(Agent.TempDirectory)/**/coverage.cobertura.xml
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: 'src/EnergySavingMode/*.csproj'
      nobuild: true
      versioningScheme: byBuildNumber
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      publishLocation: 'pipeline'
      artifact: 'nuget'

- deployment: CD
  dependsOn: CI
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  environment: 'Azure'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: NuGetCommand@2
          displayName: 'NuGet push'
          inputs:
            command: 'push'
            packagesToPush: '$(Pipeline.Workspace)/nuget/*.nupkg'
            nuGetFeedType: 'external'
            publishFeedCredentials: 'Azure DevOps nuget publish'
