# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  Major: '0'
  Minor: '0'
  Patch: '1'

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: CI
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '*.sln'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '*.sln'
      arguments: '--no-build --no-restore'
  - task: DotNetCoreCLI@2
    inputs:
        command: pack
        arguments: '--no-build --no-restore --output $(Build.ArtifactStagingDirectory)'
        versioningScheme: byPrereleaseNumber
        majorVersion: '$(Major)'
        minorVersion: '$(Minor)'
        patchVersion: '$(Patch)'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      publishLocation: 'pipeline'
      artifact: 'nuget'

- deployment: CD
  dependsOn: CI
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  environment: 'Azure'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: NuGetCommand@2
          displayName: 'NuGet push'
          inputs:
            command: push
            nuGetFeedType: external
            publishFeedCredentials: nuget.org
            packagesToPush: '$(Pipeline.Workspace)/nuget/*.nupkg'